### PR TITLE
The following fields have been hidden:

### PR DESCRIPTION
**Pull request by DeniE46**
Номер участък
Първостепенно местообитание
Второстепенно местообитание
Посещение номер

The fields in landscape have been moved out of <TableRow> so as to not take space inside

### CODE REVIEW

**Review by onyxvd — CHANGES_REQUESTED** [review]
These fields won't be used anymore, so it is better to remove all the logic related to them.
Also, you can provide some screenshots since there are UI changes.

**Comment by DeniE46** [comment]
Attaching screenshots that reflect recent changes
[
Screenshot_20210414-130921_SmartBirds Pro
Screenshot_20210414-104945_SmartBirds Pro
Screenshot_20210414-110042_SmartBirds Pro


](url)

**Review by onyxvd — CHANGES_REQUESTED** [review]
Everything is ok! Just one thing... I think you can also remove the prefs from CbmPrefs related to these fields since we don't need to store the last value used anymore.

**Comment by DeniE46** [comment]
Fields from CbmPrefs are now also removed

**Review by onyxvd — APPROVED** [review]

**Review by groupsky — APPROVED** [review]
lgtm

**Pull request merged**
